In [13]:
import csv
import pandas as pd
from itertools import product
c=0
data_follower=pd.read_csv('/home/shuham/Desktop/Projects/NSW/NSW_Kashmir/#GameofThrones_follower_followee_network.csv')
data_tweet= pd.read_csv('/home/shuham/Desktop/Projects/NSW/NSW_Kashmir/#GameofThrones_tweets.csv')

# with open('/home/shuham/Desktop/ayodhyahearing_follower_network_new.csv') as f:
#     spamreader = csv.reader(f, delimiter=',')
# #     for k, m in [(t, s) for i, *j in spamreader for t, s in product(i, j)]:
# #         if len(m)!=0 :
# #             print (k, m)
# #             c=c+1
#     for row in spamreader:
#         for i in row:
#             if not m:
#                 print(row[0],i)

In [14]:
data_tweet.head()

,user_id,status_id,created_at,screen_name,text,source,display_text_width,reply_to_status_id,reply_to_user_id,reply_to_screen_name,...,statuses_count,favourites_count,account_created_at,verified,profile_url,profile_expanded_url,account_lang,profile_banner_url,profile_background_url,profile_image_url
0,x3041702170,x1198338364640055303,2019-11-23 20:31:44,brxvwndr,#Domina\n\nðŸ”´NOVEDADðŸ”´\n\nLa nueva serie de la A...,Twitter for iPad,140,NaN,NaN,NaN,...,196162,8161,2015-02-17 00:02:13,False,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/30417021...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1196057202...
1,x1069638973943947268,x1198338001883009026,2019-11-23 20:30:18,RebeccaCann23,Available to pre order now.\nGame Of Thrones t...,Twitter for Android,140,NaN,NaN,NaN,...,30282,50103,2018-12-03 17:06:19,False,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/10696389...,NaN,http://pbs.twimg.com/profile_images/1138813132...
2,x1886897922,x1198337996933742592,2019-11-23 20:30:17,WOODStheMAV,She is savage in real life too. #GameofThrones...,Twitter for Android,85,NaN,NaN,NaN,...,1908,1731,2013-09-20 15:44:31,False,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/18868979...,http://abs.twimg.com/images/themes/theme1/bg.png,http://pbs.twimg.com/profile_images/1190302785...
3,x15807157,x1198337982018646016,2019-11-23 20:30:13,bucketree,Glad you have spoken out #EmiliaClark #mothero...,Twitter for iPad,86,NaN,NaN,NaN,...,15660,7837,2008-08-11 11:28:02,False,http://t.co/3ttfnIpTZ1,http://www.thecatalystcollective.co.nz,NaN,https://pbs.twimg.com/profile_banners/15807157...,http://abs.twimg.com/images/themes/theme9/bg.gif,http://pbs.twimg.com/profile_images/4784260519...
4,x273119117,x1198337702812405762,2019-11-23 20:29:07,gipsipink,Available to pre order now.\nGame Of Thrones t...,Twitter for Android,140,NaN,NaN,NaN,...,127973,50903,2011-03-27 21:37:35,False,NaN,NaN,NaN,https://pbs.twimg.com/profile_banners/27311911...,http://abs.twimg.com/images/themes/theme11/bg.gif,http://pbs.twimg.com/profile_images/1164264300...

In [15]:
userid_screen_name= data_tweet[['user_id','screen_name']]
dict={}
# data3.iloc[0][0]
# data3.iloc[1][1]
c=len(userid_screen_name)
for i in range(c):
    dict[userid_screen_name.iloc[i][0][1:]]=userid_screen_name.iloc[i][1]
# for i in dict:
#     print(type(i))

In [16]:
retweet=data_tweet[['screen_name','retweet_screen_name']]
retweet=retweet.fillna(0)
retweet

       screen_name retweet_screen_name
0         brxvwndr     PreviouslySerix
1    RebeccaCann23            _DCWorld
2      WOODStheMAV           chichhora
3        bucketree                   0
4        gipsipink            _DCWorld
..             ...                 ...
195    freefolkbot                   0
196        arbust0                   0
197  vrojas33172_v     CreativeParTees
198   SHIELD221287                   0
199      Gr33nHand                   0

[200 rows x 2 columns]

In [17]:
file_handler=open("/home/shuham/Desktop/retweet_GOT.txt","a+") 
c=len(retweet)
counter=0
for i in range(c):
    if retweet.iloc[i][1]==0:
        continue
    else:
        file_handler.write(retweet.iloc[i][0]+" "+retweet.iloc[i][1]+"\n")
        counter=counter+1
file_handler.close()

In [18]:
counter

117

In [19]:
screen_followerId=data_follower[['screen_name','followerIDs']]
screen_followerId.head()

     screen_name                                        followerIDs
0       brxvwndr  1075369607354089472, 1196100072754335744, 2361...
1  RebeccaCann23  1039125654120407042, 992445387070955521, 11405...
2    WOODStheMAV  3310986846, 371482444, 1139513551935213568, 29...
3      bucketree  1074177396897734656, 1149680900956971008, 7332...
4      gipsipink  1188364350282752000, 1092123642719334401, 1181...

In [9]:
import math
followerId=screen_followerId['followerIDs']
list_follwerId=followerId.str.split(",")
names=screen_followerId['screen_name']
names[0]
list_follwerId

0      [1075369607354089472,  1196100072754335744,  2...
1      [1039125654120407042,  992445387070955521,  11...
2      [3310986846,  371482444,  1139513551935213568,...
3      [1074177396897734656,  1149680900956971008,  7...
4      [1188364350282752000,  1092123642719334401,  1...
                             ...
184    [787440720764297216,  1195440631293890561,  78...
185    [1184990245617590274,  776942985053294592,  95...
186    [545235190,  1066882865135259648,  2700077027,...
187    [1197555200355004416,  1197555007559626753,  1...
188    [24486579,  283852544,  298134241,  397220722,...
Name: followerIDs, Length: 189, dtype: object

In [12]:
file1 = open("/home/shuham/Desktop/Projects/NSW/NSW_Kashmir/gameOfThrones_follower_edgelist.txt","a") 
c=0
counter=0
for item in list_follwerId:
    for i in item:
        if i in dict:
            #print(names[c],i)
            print(dict[i]+" "+i+" "+names[c])
            file1.write(""+dict[i]+" "+i+"\n")
            counter=counter+1
    c=c+1
file1.close()