In [10]:
import csv
import pandas as pd
from itertools import product
import pandas as pd
import numpy as np
import random as rd
import matplotlib.pyplot as plt
import csv
c=0
data_follower=pd.read_csv('/home/shuham/Desktop/Projects/NSW/NSW_Kashmir/#Kashmir_follower_followee_network.csv')
data_tweet= pd.read_csv('/home/shuham/Desktop/Projects/NSW/NSW_Kashmir/#Kashmir_tweets.csv')

In [11]:
data_tweet.columns

Index(['user_id', 'status_id', 'created_at', 'screen_name', 'text', 'source',
       'display_text_width', 'reply_to_status_id', 'reply_to_user_id',
       'reply_to_screen_name', 'is_quote', 'is_retweet', 'favorite_count',
       'retweet_count', 'hashtags', 'symbols', 'urls_url', 'urls_t.co',
       'urls_expanded_url', 'media_url', 'media_t.co', 'media_expanded_url',
       'media_type', 'ext_media_url', 'ext_media_t.co',
       'ext_media_expanded_url', 'ext_media_type', 'mentions_user_id',
       'mentions_screen_name', 'lang', 'quoted_status_id', 'quoted_text',
       'quoted_created_at', 'quoted_source', 'quoted_favorite_count',
       'quoted_retweet_count', 'quoted_user_id', 'quoted_screen_name',
       'quoted_name', 'quoted_followers_count', 'quoted_friends_count',
       'quoted_statuses_count', 'quoted_location', 'quoted_description',
       'quoted_verified', 'retweet_status_id', 'retweet_text',
       'retweet_created_at', 'retweet_source', 'retweet_favorite_count',
       'retweet_retweet_count', 'retweet_user_id', 'retweet_screen_name',
       'retweet_name', 'retweet_followers_count', 'retweet_friends_count',
       'retweet_statuses_count', 'retweet_location', 'retweet_description',
       'retweet_verified', 'place_url', 'place_name', 'place_full_name',
       'place_type', 'country', 'country_code', 'geo_coords', 'coords_coords',
       'bbox_coords', 'status_url', 'name', 'location', 'description', 'url',
       'protected', 'followers_count', 'friends_count', 'listed_count',
       'statuses_count', 'favourites_count', 'account_created_at', 'verified',
       'profile_url', 'profile_expanded_url', 'account_lang',
       'profile_banner_url', 'profile_background_url', 'profile_image_url'],
      dtype='object')

In [12]:
filtered_data = data_tweet[['user_id','screen_name','lang','followers_count','friends_count','profile_url','description','location']]
#filtered_data=filtered_data.fillna(0)
filtered_data['ratio']=filtered_data['followers_count']/filtered_data['friends_count']
filtered_data

/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,user_id,screen_name,lang,followers_count,friends_count,profile_url,description,location,ratio
0,x1167337853581348864,JKPNA1,en,28,2,https://t.co/WF4UWYGfQj,Official Account of Jammu Kashmir People's Nat...,NaN,14.000000
1,x38930724,GoPeaceWay,en,322,3319,https://t.co/RVmkiJX4xq,Professional Student,United States,0.097017
2,x921238936726282240,AbdurRehman1918,ur,1228,1017,NaN,‚Äè‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé#ÿØÿπŸàÿ™_Ÿà_ÿßÿµŸÑÿßÿ≠ \n‚Äè‚Äè#Muslim #Pakistani,"Rawalpindi, Pakistan",1.207473
3,x921238936726282240,AbdurRehman1918,ur,1228,1017,NaN,‚Äè‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé‚Äé#ÿØÿπŸàÿ™_Ÿà_ÿßÿµŸÑÿßÿ≠ \n‚Äè‚Äè#Muslim #Pakistani,"Rawalpindi, Pakistan",1.207473
4,x736161488591847424,MoFaisu,en,103,44,NaN,Pakistani üáµüá∞ & Kashmiri üèûÔ∏è \nMember of @PTFP_O...,Dadyal Islamabad kashmir,2.340909
...,...,...,...,...,...,...,...,...,...
195,x867231958828548096,kunte_v,en,91,171,NaN,‡§ú‡§¨ ‡§§‡•Å‡§Æ ‡§™‡•à‡§¶‡§æ ‡§π‡•Å‡§è ‡§•‡•á ‡§§‡•ã ‡§§‡•Å‡§Æ ‡§∞‡•ã‡§è ‡§•‡•á\n‡§ú‡§¨‡§ï‡§ø ‡§™‡•Ç‡§∞‡•Ä ‡§¶‡•Å...,"Gwalior, India",0.532164
196,x2149082660,bantophool,en,3,94,NaN,Slowly woke up to the fact that we need real c...,NaN,0.031915
197,x3021883369,Chadhar563,en,107,517,NaN,NaN,NaN,0.206963
198,x2200838298,akashsinghaero,en,6,45,NaN,NaN,‡§≠‡§æ‡§∞‡§§,0.133333
199,x1101026258941546502,ShafiqShehzada,ur,597,917,https://t.co/4JsN3k8KNt,"IF you Feel Like you are Losing Everything, Re...",Dera Ghazi Khan,0.651036

In [13]:
for i in range(200):
    if filtered_data['ratio'][i] >=0.45 and filtered_data['ratio'][i]<=0.55:
        filtered_data['ratio'][i]=1
        print(i)
    else:
        filtered_data['ratio'][i]=0
        
        
filtered_data['ratio'][95]

11
59
63
64
66
67
100
101
102
106
112
157
195

/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/shuham/.local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3326: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

0.0

In [14]:
#filtered_data.loc[:,['user_id']]
filtered_data['user_id'] = np.where(filtered_data['user_id'].isnull(), 0, 1)
filtered_data['screen_name'] = np.where(filtered_data['screen_name'].isnull(), 0, 1)
filtered_data['lang'] = np.where(filtered_data['lang']!="en", 0, 1)
filtered_data['followers_count'] = np.where(filtered_data['followers_count']>1000,0,filtered_data['followers_count'])
filtered_data['followers_count'] = np.where(filtered_data['followers_count']<30,0,1)

filtered_data['friends_count'] = np.where(filtered_data['friends_count']>1200, 0, 1)
filtered_data['profile_url'] = np.where(filtered_data['profile_url'].isnull(), 0, 1)
filtered_data['description'] = np.where(filtered_data['description'].isnull(), 0, 1)
filtered_data['location'] = np.where(filtered_data['location'].isnull(), 0, 1)

filtered_data

/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/home/shuham/.local/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,user_id,screen_name,lang,followers_count,friends_count,profile_url,description,location,ratio
0,1,1,1,0,1,1,1,0,0.0
1,1,1,1,1,0,1,1,1,0.0
2,1,1,0,0,1,0,1,1,0.0
3,1,1,0,0,1,0,1,1,0.0
4,1,1,1,1,1,0,1,1,0.0
...,...,...,...,...,...,...,...,...,...
195,1,1,1,1,1,0,1,1,1.0
196,1,1,1,0,1,0,1,0,0.0
197,1,1,1,1,1,0,0,0,0.0
198,1,1,1,0,1,0,0,1,0.0
199,1,1,0,1,1,1,1,1,0.0

In [15]:
from sklearn.cluster import KMeans

In [17]:

kmeans = KMeans(n_jobs = -1, n_clusters = 2, init='k-means++',max_iter=1000)
kmeans.fit(X=filtered_data)
pred = kmeans.predict(filtered_data)

In [18]:
kmeans.inertia_

165.76802572881004

In [19]:
frame = pd.DataFrame(filtered_data) 
frame['cluster'] = pred 
frame['cluster'].value_counts()

1    119
0     81
Name: cluster, dtype: int64

In [20]:
c1=[]
for i in range(200):
    if frame['cluster'][i]==1:
        #print(data_tweet['screen_name'][i])
        #list_b.append(data_tweet['screen_name'][i])
        c1.append(frame.iloc[i])
        
df0=pd.DataFrame(c1)
df0
#print("Ration parameter is less than 0 for entire cluster, so focusing on cluster 0")

,user_id,screen_name,lang,followers_count,friends_count,profile_url,description,location,ratio,cluster
4,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
5,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
6,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
8,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
9,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
193,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
194,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
195,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
197,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
199,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0

In [21]:
c0=[]
for i in range(200):
    if frame['cluster'][i]==0:
        #print(data_tweet['screen_name'][i])
        #list_b.append(data_tweet['screen_name'][i])
        c0.append(frame.iloc[i])
        
df1=pd.DataFrame(c0)
df1

,user_id,screen_name,lang,followers_count,friends_count,profile_url,description,location,ratio,cluster
0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
1,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0
2,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
3,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
7,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
190,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
191,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
192,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
196,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
198,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [73]:
possible_bots=[] 
for i in range(200):
    try:
        if(df0['ratio'][i]==1):
            #print("inside ratio")
            if(df0['location'][i]==0):
                #print("inside loc")
                if(df0['followers_count'][i]==1):
                    if(df0['description'][i]==1):
                        print(data_tweet['screen_name'][i]+" "+data_tweet['user_id'][i]+" "
                              +data_tweet['created_at'][i]+" "+data_tweet['text'][i])
    except:
        continue

vaid_abhay x2523227912 2019-11-06 06:40:17 @Rohietgupta Bro all happens in politics check out #Kashmir #Sikkim #Haryana justifying this issue is not in comman mans mind
MundaKoshur x1100277547953258502 2019-11-06 06:35:22 @MundaKoshur's account has been withheld in India in response to a legal demand. Learn more.
Ghost1455673598 x1160907523978866688 2019-11-06 06:34:38 #Kashmir‚ÄîDay 95

-Internet blocked
-Pre-paid mobile services blocked
-Businesses partially-closed, ‚Ç® 11k crore loss
-Schools/Colleges deserted
-Public transport off roads
-IT sector dead
-Tourism down by 85%
-100k job losses
-1000s in jails, untraceable
-Mental distress on rise
Crrazy_gamerz x4767196763 2019-11-06 06:34:37 Massive turnout of youths (both Boys and Girls ) in SPO recruitment rally of @JmuKmrPolice in Poonch.
One #kashmirkibeti said - There is huge unemployment in J&amp;K , we want to join Police not to just get job but to serve our country.
#Kashmir #Poonch #SPO #JaiHind
graziosco x1081781924274663425 2019-11-06 06:32:24 #Kashmir: Vrinda Grover also places reliance on Article 19 of ICCPR.
graziosco x1081781924274663425 2019-11-06 06:32:22 #Kashmir: Today internet is an essential and basic attribute of freedom of press. It enables media to peform its role in a democracy.

Any interference with that is violative of freedom of press, Vrinda Grover.
graziosco x1081781924274663425 2019-11-06 06:32:19 #Kashmir: Hearing in plea by Anuradha Bhasin on communication shutdown in Kashmir continuing before court 3 of Supreme Court.

Vrinda Grover arguing for Bhasin.

"Shutdown for 90 days is by no means a temporary measure" , Vrinda Grover.

In [71]:
bots=pd.DataFrame(possible_bots)

In [72]:
bots

                                                   0
0  vaid_abhay x2523227912 2019-11-06 06:40:17 @Ro...
1  MundaKoshur x1100277547953258502 2019-11-06 06...
2  Ghost1455673598 x1160907523978866688 2019-11-0...
3  Crrazy_gamerz x4767196763 2019-11-06 06:34:37 ...
4  graziosco x1081781924274663425 2019-11-06 06:3...
5  graziosco x1081781924274663425 2019-11-06 06:3...
6  graziosco x1081781924274663425 2019-11-06 06:3...

In [22]:
import botometer

In [23]:
rapidapi_key = "9ec2290368mshfa0ba97cff0c490p1de196jsn16c6d795de7a" # now it's called rapidapi key
twitter_app_auth = {
    'consumer_key': 'HDxI8l3dRXJExUjMhH3hOOpe9',
    'consumer_secret': 'wreDXDdGq07sudOZZcJ9wNEqCNNd5S7WY3FJ4PvvzZlaUskxfx',
    'access_token': '2842437144-0X01WDpjmkJxDNZX7GIcDEubVThY2XCJsLNAhyk',
    'access_token_secret': 'gzDTtTyyA2fbJ60RQwlnxPqnpHEU2EsYnTBxk3JoCuukM',
  }

In [24]:
bom = botometer.Botometer(wait_on_ratelimit=True,
                          rapidapi_key=rapidapi_key,
                          **twitter_app_auth)

In [25]:
result = bom.check_account('graziosco')
result

{'cap': {'english': 0.02470203924309943, 'universal': 0.021041094138717433},
 'categories': {'content': 0.2476527136758392,
  'friend': 0.20957193071779157,
  'network': 0.44801550652707667,
  'sentiment': 0.3194385725802404,
  'temporal': 0.11725226041842143,
  'user': 0.3505040922700097},
 'display_scores': {'content': 1.2,
  'english': 1.4,
  'friend': 1.0,
  'network': 2.2,
  'sentiment': 1.6,
  'temporal': 0.6,
  'universal': 1.3,
  'user': 1.8},
 'scores': {'english': 0.28621206238390096, 'universal': 0.25152334764543},
 'user': {'id_str': '1081781924274663425', 'screen_name': 'graziosco'}}

In [26]:
result['cap']

{'english': 0.02470203924309943, 'universal': 0.021041094138717433}

In [27]:
screen_name=filtered_data['screen_name']
screen_name

0      1
1      1
2      1
3      1
4      1
      ..
195    1
196    1
197    1
198    1
199    1
Name: screen_name, Length: 200, dtype: int64

In [28]:
import tweepy
type(screen_name)

pandas.core.series.Series

In [29]:
# for i in screen_name:
#     print(i)
results={}

In [30]:
c=0
for i in screen_name:
    try:
        result[i]=bom.check_account(i)
        c=c+1
        print(c)
    except tweepy.TweepError:
        print("Failed to run the command on that user, Skipping...")

Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...

Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...
Failed to run the command on that user, Skipping...

In [31]:
result

{'cap': {'english': 0.02470203924309943, 'universal': 0.021041094138717433},
 'categories': {'content': 0.2476527136758392,
  'friend': 0.20957193071779157,
  'network': 0.44801550652707667,
  'sentiment': 0.3194385725802404,
  'temporal': 0.11725226041842143,
  'user': 0.3505040922700097},
 'display_scores': {'content': 1.2,
  'english': 1.4,
  'friend': 1.0,
  'network': 2.2,
  'sentiment': 1.6,
  'temporal': 0.6,
  'universal': 1.3,
  'user': 1.8},
 'scores': {'english': 0.28621206238390096, 'universal': 0.25152334764543},
 'user': {'id_str': '1081781924274663425', 'screen_name': 'graziosco'}}

In [32]:
screen_name.tolist()

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]